"""File-backed agent trace store.

Phase 8 keeps traces as one JSON document per session under
``data/agent_traces/``. JSON-on-disk avoids a SQL migration during the
harness phase and keeps traces inspectable with ``cat`` for debugging.
A real ``pgvector`` table can come later if/when we want to search
across traces.

Naming: ``YYYYMMDDTHHMMSSZ-<short-id>.json`` so ``ls`` sorts
chronologically.
"""

from __future__ import annotations

import json
import secrets
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from src.agent.core.loop import AgentResult
from src.core.config import PROJECT_ROOT

_DEFAULT_DIR = PROJECT_ROOT / "data" / "agent_traces"


@dataclass
class TraceRecord:
    """Persisted form of an agent run."""

    id: str
    started_at: str
    finished: bool
    stop_reason: str
    goal: str
    answer: str | None
    elapsed_ms: int
    step_count: int
    tools_allowed: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    steps: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def summary(self) -> dict[str, Any]:
        """Lightweight version for list views (omits step bodies)."""
        return {
            "id": self.id,
            "started_at": self.started_at,
            "finished": self.finished,
            "stop_reason": self.stop_reason,
            "goal": self.goal,
            "answer": self.answer,
            "elapsed_ms": self.elapsed_ms,
            "step_count": self.step_count,
        }


class TraceStore:
    def __init__(self, base_dir: Path | None = None) -> None:
        self.base_dir = (base_dir or _DEFAULT_DIR).resolve()

    def save(self, record: TraceRecord) -> Path:
        self.base_dir.mkdir(parents=True, exist_ok=True)
        path = self.base_dir / f"{record.id}.json"
        path.write_text(
            json.dumps(record.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        return path

    def load(self, trace_id: str) -> TraceRecord:
        target = self._safe_path(trace_id)
        if not target.exists():
            raise FileNotFoundError(f"Trace '{trace_id}' not found.")
        data = json.loads(target.read_text(encoding="utf-8"))
        return _record_from_dict(data)

    def list(self, limit: int = 50) -> list[TraceRecord]:
        if not self.base_dir.exists():
            return []
        files = sorted(
            (p for p in self.base_dir.iterdir() if p.is_file() and p.suffix == ".json"),
            reverse=True,
        )
        out: list[TraceRecord] = []
        for path in files[:limit]:
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                continue
            out.append(_record_from_dict(data))
        return out

    def delete(self, trace_id: str) -> None:
        target = self._safe_path(trace_id)
        target.unlink(missing_ok=True)

    def _safe_path(self, trace_id: str) -> Path:
        # Trace ids are generated by us; still guard against traversal if a
        # caller forwards untrusted input here.
        if "/" in trace_id or "\\" in trace_id or ".." in trace_id:
            raise ValueError(f"Invalid trace id: {trace_id!r}")
        return self.base_dir / f"{trace_id}.json"


def make_trace_id(now: datetime | None = None) -> str:
    now = now or datetime.now(UTC)
    stamp = now.strftime("%Y%m%dT%H%M%SZ")
    return f"{stamp}-{secrets.token_hex(4)}"


def record_from_result(
    result: AgentResult,
    *,
    tools_allowed: list[str],
    metadata: dict[str, Any] | None = None,
    started_at: datetime | None = None,
    trace_id: str | None = None,
) -> TraceRecord:
    started = started_at or datetime.now(UTC)
    return TraceRecord(
        id=trace_id or make_trace_id(started),
        started_at=started.isoformat(),
        finished=result.finished,
        stop_reason=result.stop_reason,
        goal=result.goal,
        answer=result.answer,
        elapsed_ms=result.elapsed_ms,
        step_count=len(result.steps),
        tools_allowed=list(tools_allowed),
        metadata=dict(metadata or {}),
        steps=[s.to_dict() for s in result.steps],
    )


def _record_from_dict(data: dict[str, Any]) -> TraceRecord:
    return TraceRecord(
        id=data["id"],
        started_at=data["started_at"],
        finished=bool(data.get("finished")),
        stop_reason=data.get("stop_reason", ""),
        goal=data.get("goal", ""),
        answer=data.get("answer"),
        elapsed_ms=int(data.get("elapsed_ms", 0)),
        step_count=int(data.get("step_count", 0)),
        tools_allowed=list(data.get("tools_allowed", [])),
        metadata=dict(data.get("metadata", {})),
        steps=list(data.get("steps", [])),
    )
